# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# exports
# export ZSH="/root/.oh-my-zsh"
export LANG=en_US.UTF-8
export LANGUAGE=en_US

# XDG directories
export XDG_DATA_DIRS="/usr/local/share:/usr/share"
export XDG_CONFIG_DIRS="/etc/xdg"

autoload -U colors;
autoload -U promptinit;
colors && promptinit;

# source powerlevel10k if it exists
[ -d ~/.zsh ] && source ~/.zsh/powerlevel10k/powerlevel10k.zsh-theme

# Vi mode options
# bindkey -v

# init thefuck alias
eval $(thefuck --alias)

# some basic command aliases
alias rlz="source ~/.zshrc"
alias ls='ls --color'
alias chx='chmod +x'
alias snow='shutdown now'

# cargo
alias ccb='cargo clean; cargo build'
alias ccbr='cargo clean; cargo build; cargo run'

# spelling error aliases
alias :q='exit'
alias sl='echo "You spelled ls wrong"; ls'

# desktop env
alias kde='xinit /usr/bin/startplasma-x11'
alias bspwm='xinit /usr/local/bin/bspwm'

alias vim='nvim'
alias v='nvim'

alias gs='git status'
alias gcm='git commit -m'
alias gu='git pull'
alias gd='git diff'
alias gp='git push'
alias ga='git add'
alias gau='git add -u'
alias gl='git log'
alias glg='git log --graph'

# go to dotfiles folder
alias gdf='cd ~/dotfiles'

alias djd='sudo docker-compose run web psql -U django -h db postgres'
alias djm='sudo docker-compose run web python3 manage.py'
alias djs='sudo docker-compose run --service-ports web python3 manage.py runserver'
alias djt='sudo docker-compose run web pytest'
alias djr='sudo docker-compose run web'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source ~/dotfiles/zsh/startup.zsh
